-- Javni tekstovi početne (BS/EN); prazno u bazi = fallback na bundle i18n
ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS hero_category_bs text,
  ADD COLUMN IF NOT EXISTS hero_category_en text,
  ADD COLUMN IF NOT EXISTS hero_tagline_bs text,
  ADD COLUMN IF NOT EXISTS hero_tagline_en text,
  ADD COLUMN IF NOT EXISTS hero_cta_work_bs text,
  ADD COLUMN IF NOT EXISTS hero_cta_work_en text,
  ADD COLUMN IF NOT EXISTS hero_scroll_hint_bs text,
  ADD COLUMN IF NOT EXISTS hero_scroll_hint_en text,
  ADD COLUMN IF NOT EXISTS featured_kicker_bs text,
  ADD COLUMN IF NOT EXISTS featured_kicker_en text,
  ADD COLUMN IF NOT EXISTS featured_title_bs text,
  ADD COLUMN IF NOT EXISTS featured_title_en text,
  ADD COLUMN IF NOT EXISTS featured_subtitle_bs text,
  ADD COLUMN IF NOT EXISTS featured_subtitle_en text,
  ADD COLUMN IF NOT EXISTS about_kicker_bs text,
  ADD COLUMN IF NOT EXISTS about_kicker_en text,
  ADD COLUMN IF NOT EXISTS about_title_bs text,
  ADD COLUMN IF NOT EXISTS about_title_en text,
  ADD COLUMN IF NOT EXISTS about_p1_bs text,
  ADD COLUMN IF NOT EXISTS about_p1_en text,
  ADD COLUMN IF NOT EXISTS about_p2_bs text,
  ADD COLUMN IF NOT EXISTS about_p2_en text;
